#!/usr/bin/env bash
# fixing issues arrised from using docker
# make the aache server return hello holberton when quering

sudo apt-get updqte -y
sudo apt-get install -y apache2
sudo /etc/init.d/apache2 start
echo "Hello Holberton" | sudo tee -a /var/www/html/index.html
sudo /etc/init.d/apache2 restart
